---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate # Takes way too long for the account-baseline-* modules.
      - id: terraform_docs
      - id: terraform_tflint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-symlinks
